apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - helmrelease.yaml              # s√∏rg for at filendelsen matcher
  - cnp-longhorn-ui.yaml
  - service-lb.yaml
configMapGenerator:
  - name: longhorn-values
    files:
      - values.yml
    options:
      disableNameSuffixHash: true