apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/prod/elastic-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: elastic-eck-operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: elastic-operator
      namespace: elastic-system
