apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-eck
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/prod/elastic-eck
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
