---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./clusters/prod/cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
