apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - helmrepository-elastic.yaml
  - helmrepository-longhorn.yaml      # ✅ HelmRepository (charts.longhorn.io)
  - kustomization-longhorn.yaml       # ✅ Kustomization CR, der peger på ./clusters/prod/longhorn
  - kustomization-cilium-config.yaml  # ✅ Cilium LB-IPAM og L2 announcement policies